# This is a config for E2B sandbox template.
# You can use template ID (vcka2m115xyxxgm57sx7) or template name (nextjs-imsidkg) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("nextjs-imsidkg") # Sync sandbox
# sandbox = await AsyncSandbox.create("nextjs-imsidkg") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('nextjs-imsidkg')

team_id = "20e38c66-5c05-45e1-a081-9658788eb70b"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "nextjs-imsidkg"
template_id = "vcka2m115xyxxgm57sx7"
